"""add Department

Revision ID: 712958f94b0e
Revises: bac93f7fb26c
Create Date: 2024-09-05 02:38:19.447526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712958f94b0e'
down_revision = 'bac93f7fb26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
