"""rename address

Revision ID: f2401becfebc
Revises: 7fed762b5183
Create Date: 2024-09-05 02:56:04.487222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2401becfebc'
down_revision = '7fed762b5183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name= 'location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')

    # ### end Alembic commands ###
